modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/AyUpItsAli/Alis-Bean-Mod/issues"
[[mods]]
    modId="alisbeanmod"
    version="${file.jarVersion}"
    displayName="Ali's Bean Mod"
    displayURL="https://github.com/AyUpItsAli/Alis-Bean-Mod"
    logoFile="alis_bean_mod_logo.png"
    authors="AyUpItsAli"
    description='''
    The Ultimate BEAN Experience for Minecraft!
    '''
[[dependencies.alisbeanmod]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alisbeanmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.alisbeanmod]]
    modId="croptopia"
    mandatory=true
    versionRange="[2.1.0,)"
    ordering="NONE"
    side="BOTH"
