modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/AyUpItsAli/Beanology/issues"
[[mods]]
    modId="beanology"
    version="${file.jarVersion}"
    displayName="Beanology"
    displayURL="https://github.com/AyUpItsAli/Beanology"
    logoFile="beanology_logo.png"
    authors="AyUpItsAli"
    description='''
    Bean crops, bean tech and bean magic. The complete bean experience!
    '''
[[dependencies.beanology]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.beanology]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.beanology]]
    modId="croptopia"
    mandatory=true
    versionRange="[2.1.0,)"
    ordering="NONE"
    side="BOTH"
